name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # if your default branch is "master", change this to master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project pickmeservicesonline
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
